default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: dotreserve_development

test:
  <<: *default
  database: dotreserve_test

production:
  <<: *default
  database: dotreserve_production
